# Generated by Django 4.1.5 on 2023-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="price_limit",
            field=models.FloatField(default=0, verbose_name="Price Limit"),
        ),
    ]
