# Generated by Django 4.1.5 on 2023-07-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="redirect_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Redirect URL"
            ),
        ),
    ]
