# Generated by Django 4.1.5 on 2023-06-23 19:57

import backend.models.image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_new",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.models.image.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
