# Generated by Django 4.1.5 on 2023-02-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Extra Data"
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=1024, unique=True, verbose_name="name"),
                ),
                ("value", models.CharField(max_length=1024, verbose_name="value")),
            ],
            options={
                "verbose_name": "System Config",
                "verbose_name_plural": "System Configs",
            },
        ),
    ]
