# Generated by Django 4.1.5 on 2023-02-27 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_systemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_otp",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(6),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Email OTP",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="No of Failed Login Attempts",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_otp",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(6),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Phone OTP",
            ),
        ),
    ]
