# Generated by Django 4.1.5 on 2023-06-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_image_image_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.URLField(
                blank=True, null=True, verbose_name="Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_new",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/", verbose_name="Image"
            ),
        ),
    ]
