# Generated by Django 4.1.5 on 2023-07-09 17:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_banner_redirect_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="values",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=128),
                blank=True,
                max_length=2048,
                null=True,
                size=None,
            ),
        ),
    ]
