# Generated by Django 4.1.5 on 2023-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_question_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_user_verified",
            field=models.BooleanField(
                default=False, verbose_name="Is User Verified"
            ),
        ),
    ]
