# Generated by Django 4.1.5 on 2023-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_image_image_alter_image_image_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="image_data",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banner/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon_data",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="category/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="icon_data",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="service/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.URLField(
                blank=True, null=True, verbose_name="Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.URLField(
                blank=True, null=True, verbose_name="Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.URLField(
                blank=True, null=True, verbose_name="Image URL"
            ),
        ),
    ]
