# Generated by Django 4.1.5 on 2023-06-24 14:51

import backend.models.image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_banner_image_data_category_icon_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_new",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.models.image.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
