# Generated by Django 4.1.5 on 2023-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_user_email_otp_alter_user_phone_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="pincode",
            field=models.CharField(max_length=128, verbose_name="pincode"),
        ),
    ]
