# Generated by Django 4.1.5 on 2023-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_user_is_user_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Name"
            ),
        ),
    ]
