# Generated by Django 4.1.5 on 2023-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_alter_area_pincode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Area", "verbose_name_plural": "Area"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"verbose_name": "State", "verbose_name_plural": "States"},
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="pincode",
            field=models.CharField(max_length=128, verbose_name="Pincode"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="key",
            field=models.CharField(
                max_length=1024, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="value",
            field=models.CharField(max_length=1024, verbose_name="Value"),
        ),
    ]
