# Generated by Django 4.1.5 on 2023-06-24 15:42

import backend.models.banner
import backend.models.category
import backend.models.service
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_alter_image_image_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image_data",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.models.banner.upload_to,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_data",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.models.category.upload_to,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_data",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.models.service.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
