# Generated by Django 4.1.5 on 2023-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_banner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("User", "User"),
                    ("Guest", "Guest"),
                ],
                max_length=128,
                verbose_name="role",
            ),
        ),
    ]
