# Generated by Django 4.1.5 on 2023-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0006_alter_banner_image_data_alter_category_icon_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="sequence",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Sequence"
            ),
        ),
    ]
