# Generated by Django 4.1.5 on 2023-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_users",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Blocked users"
            ),
        ),
    ]
