# Generated by Django 4.1.5 on 2023-03-24 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_area_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to="",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_category",
                        to="backend.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=128, upload_to="", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="UserAd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "tags",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=10),
                        max_length=256,
                        size=None,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="name"),
                ),
                ("price", models.FloatField(default=0, verbose_name="name")),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_area",
                        to="backend.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_category",
                        to="backend.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="backend.image",
                        verbose_name="Images",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserAd",
                "verbose_name_plural": "UserAds",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=128, verbose_name="Description"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to="",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="backend.image",
                        verbose_name="Images",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="SavedAd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_ad_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "user_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_ad",
                        to="backend.userad",
                        verbose_name="UserAd",
                    ),
                ),
            ],
            options={
                "verbose_name": "SavedAd",
                "verbose_name_plural": "SavedAds",
            },
        ),
    ]
