# Generated by Django 4.1.5 on 2023-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_banner_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
