# Generated by Django 4.1.5 on 2023-03-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_category_image_userad_service_savedad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_category",
                to="backend.category",
                verbose_name="Category",
            ),
        ),
    ]
