# Generated by Django 4.1.5 on 2023-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_category_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userad",
            name="code",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="userad",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="userad",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Is Featured"
            ),
        ),
        migrations.AlterField(
            model_name="userad",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="userad",
            name="price",
            field=models.FloatField(default=0, verbose_name="Price"),
        ),
    ]
