# Generated by Django 4.1.5 on 2023-04-01 17:51

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_category_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="category",
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                max_length=1024,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="service",
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_otp",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(111111),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name="Email OTP",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_otp",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(111111),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name="Phone OTP",
            ),
        ),
    ]
