# Generated by Django 4.1.5 on 2023-04-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_category",
                to="backend.category",
                verbose_name="Category",
            ),
        ),
    ]
