# Generated by Django 4.1.5 on 2023-04-10 17:10

import backend.utils.services
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to=backend.utils.services.get_file_path,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                max_length=1024,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to=backend.utils.services.get_file_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to=backend.utils.services.get_file_path,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to=backend.utils.services.get_file_path,
                verbose_name="Profile Image",
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Is deleted instance"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active instance"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                ("redirect_url", models.URLField(verbose_name="Redirect URL")),
                (
                    "image",
                    models.ImageField(
                        max_length=1024,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to=backend.utils.services.get_file_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_area",
                        to="backend.area",
                        verbose_name="Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
    ]
