# Generated by Django 4.1.5 on 2023-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_alter_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="sequence",
            field=models.PositiveIntegerField(default=0, verbose_name="Sequence"),
        ),
    ]
