# Generated by Django 4.1.5 on 2023-04-28 14:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_alter_userad_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_limit",
            field=models.PositiveIntegerField(
                default=128, verbose_name="Answer character limit"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="field_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Text", "Text"),
                    ("Number", "Number"),
                    ("Dropdown", "Dropdown"),
                ],
                default="Text",
                max_length=128,
                null=True,
                verbose_name="Field Type",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_required",
            field=models.BooleanField(
                default=False, verbose_name="Is Required"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="label",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="placeholder",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Placeholder",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="values",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=128),
                blank=True,
                max_length=1024,
                null=True,
                size=None,
            ),
        ),
    ]
