# Generated by Django 4.1.5 on 2023-05-05 18:48

import backend.utils.services
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_alter_question_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to=backend.utils.services.get_file_path,
                verbose_name="Image",
            ),
        ),
    ]
