# Generated by Django 4.1.5 on 2023-05-05 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
    ]
