# Generated by Django 4.1.5 on 2023-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_remove_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AddField(
            model_name="category",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AddField(
            model_name="service",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AddField(
            model_name="user",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
    ]
