# Generated by Django 4.1.5 on 2023-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_banner_url_category_url_service_url_user_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
    ]
