# Generated by Django 4.1.5 on 2023-05-05 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_alter_banner_image_alter_category_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="url",
        ),
        migrations.RemoveField(
            model_name="category",
            name="url",
        ),
        migrations.RemoveField(
            model_name="service",
            name="url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="url",
        ),
    ]
