# Generated by Django 4.1.5 on 2023-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0025_remove_banner_url_remove_category_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_price",
            field=models.BooleanField(default=True, verbose_name="Is Price Required"),
        ),
    ]
