from django.urls import path
from ..views import (
    state,
    system_config,
    location,
    user,
    area,
    category,
    user_ad,
    saved_ad,
    service,
    question,
    answer,
    image,
    banner,
)


urlpatterns = [
    path("state/", state.state_list),
    path("state/<int:pk>/", state.state_details),
    path("system-config/", system_config.system_config_list),
    path("system-config/<int:pk>/", system_config.system_config_details),
    path("location/", location.location_list),
    path("location/public/", location.public_location_list),
    path("location/<int:pk>/", location.location_details),
    path("area/", area.area_list),
    path("area/public/", area.public_area_list),
    path("area/<int:pk>/", area.area_details),
    path("user/", user.user_list),
    path("user/<int:pk>/", user.user_details),
    path("user/image/<int:pk>/", user.user_image_upload),
    path("admin/user/<int:pk>/", user.user_details_admin),
    path("user/signup/", user.signup),
    path("user/login/", user.login),
    path("user/<int:pk>/verify-otp/", user.verify_otp),
    path("user/<int:pk>/change-password/", user.change_password),
    path("category/", category.category_list),
    path("category/user/", category.category_list_user),
    path("category/<int:pk>/", category.category_details),
    path("category/icon/<int:pk>/", category.category_icon_upload),
    path("user-ad/", user_ad.user_ad_list),
    path("user-ad/<int:pk>/", user_ad.user_ad_details),
    path("saved-ad/", saved_ad.saved_ad_list),
    path("saved-ad/<int:pk>/", saved_ad.saved_ad_details),
    path("service/", service.service_list),
    path("service/user/", service.service_list_user),
    path("service/<int:pk>/", service.service_details),
    path("service/icon/<int:pk>/", service.service_icon_upload),
    path("question/", question.question_list),
    path("question/<int:pk>/", question.question_details),
    path("question/user/", question.question_list_user),
    path("answer/", answer.answer_list),
    path("answer/<int:pk>/", answer.answer_details),
    path("image/", image.image_upload),
    path("image/v2/", image.image_upload_v2),
    path("banner/", banner.banner_list),
    path("banner/user/", banner.banner_list_user),
    path("banner/<int:pk>/", banner.banner_details),
    path("banner/image/<int:pk>/", banner.banner_image_upload),
]
